apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fleetdm.fullname" . }}
  labels:
    {{- include "fleetdm.labels" . | nindent 4 }}
type: Opaque
stringData:
  FLEET_AUTH_JWT_KEY: {{ .Values.fleet.secrets.jwtKey | quote }}
  FLEET_MYSQL_PASSWORD: {{ .Values.mysql.auth.password | quote }}
  FLEET_MYSQL_ADDRESS: {{ printf "%s:3306" (include "fleetdm.mysqlHost" .) | quote }}
  FLEET_MYSQL_DATABASE: {{ .Values.mysql.auth.database | quote }}
  FLEET_MYSQL_USERNAME: {{ .Values.mysql.auth.username | quote }}
  FLEET_REDIS_ADDRESS: {{ printf "%s:6379" (include "fleetdm.redisHost" .) | quote }}
